services:
  db:
    container_name: social
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - social:/var/lib/postgresql/data

volumes:
  social: {}